application:
  image: busybox
  volumes:
  - ./codebase:/var/www/html
  - /var/lib/mysql
  tty: true

db:
  image: mariadb:5
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wordpress
    MYSQL_PASSWORD: wordpress
  ports:
  - 3306:3306
  volumes:
    - ./scripts/db:/docker-entrypoint-initdb.d
#    - ./logs/mysql:/var/log
  volumes_from:
    - application

php:
  build: provision/php-fpm
  ports:
  - 9000:9000
  volumes:
  - ./logs/php:/var/log/php5
  - ./provision/php-fpm/wp-config-local.php:/var/www/html/wp-config-local.php
  volumes_from:
  - application
  links:
  - db
  - mail

nginx:
  build: provision/nginx
  ports:
  - 8080:80
  links:
  - php
  volumes_from:
  - application
  volumes:
  - ./logs/nginx/:/var/log/nginx
  - ./provision/nginx/snippets:/etc/nginx/snippets

varnish:
  build: provision/varnish
  ports:
  - 80:80
  links:
  - nginx:backend
  environment:
    #CONTENT: "-b backend:80"
    #CONTENT: "-f /etc/varnish/simple.vcl"
    CONTENT: "-f /etc/varnish/default_3.0.vcl"
    BACKEND_PORT: 80
    VARNISH_OPTS: -T 0.0.0.0:6082 -p esi_syntax=0x2 -p cli_buffer=16384
  volumes:
  - ./provision/varnish/etc:/etc/varnish

mail:
  image: munkyboy/fakesmtp
  volumes:
  - ./logs/mail:/var/mail
